<?php
    $notificaciones;
    #Notificaciones de solicitud
    $notificaciones[-3] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Algun campo del formulario no se envio de forma correcta.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[-2] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Metodo POST no detectado.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[-1] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">La solicitud no pudo ser registrada, error del sistema.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[0] = '<div class="alert alert-success alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Registrado correctamente. <br>Dentro de 48 horas podras ver el resultado de tu sulicitud al iniciar sesión.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[1] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;");">La boleta ingresada ya se encuentra registrada, debe solicitar renovación.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[2] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">El correo ingresado ya se encuentra en uso. Selecciona otro o solicita renovación de casillero con el correo ingresado.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[3] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">El usuario ingresado ya se encuentra en uso, selecciona otro.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[4] = '<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Registrado correctamente, sin embargo, los casilleros estan agotados, entraste a la lista de espera.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[5] = '<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Actualmente te encuentras en lista de espera por lo que no puedes solicitar una renovación.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[6] = '<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Actualmente no necesitas renovación. Inicia sesión y consulta el estado de tu cuenta.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[7] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Usuario incorrecto.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[8] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Correo incorrecto.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[9] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Contraseña incorrecta.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[10] = '<div class="alert alert-success alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Solicitud de renovación completada.<br>Tienes 24 horas para subir tu comprobante de pago, de lo contrario, se reasignara tu casillero.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[11] = '<div class="alert alert-success alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Solicitud de renovación completada. Debido a que no renovaste tu casillero, se te asignara otro.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[12] = '<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">La renovación no procedió debido a que no renovaste tu antiguo casillero y en este momento no hay casilleros disponibles. Te encuentras en lista de espera.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[13] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">El casillero seleccionado no coincide con el casillero que tienes registrado.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    
    #Notificaciones de login usuario
    $notificaciones[20] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Usuario no encontrado<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[21] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Usuario o contraseña incorrecta<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[22] = '<div class="alert alert-warning alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Actualmente tu cuenta no tiene una sesión habilitada, solicita un casillero o intentalo más tarde.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
    $notificaciones[23] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">No aceptaste los términos y condiciones del casillero que se te asigno por lo que se reasigno ese casillero, puedes realizar una solicitud de casillero nuevamente.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';

    #Cierre de sesion
    $notificaciones[100] = '<div class="alert alert-success alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Cerraste sesión<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';

    #Acceso sin sesión
    $notificaciones[200] = '<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: min(60rem, 100%); margin: 3rem auto; text-align: center;">Acceso denegado, debes iniciar sesión para poder acceder.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></div>';
?>